### ISSUE TITLE
Ros2 CI Noble vs Jammy buildtime investigation

### ISSUE THREAD

**Issue by Crola1702** [osrf/buildfarm-tools#52]
Nightly Linux buildtimes have changed significantly in since Noble transition.

This is a tracker of general findings about this situation.

> **Note**
> I'm working on [buildlog-time-metrics](https://github.com/osrf/buildfarm-tools/tree/Crola1702/buildlog-time-metrics) branch to gather all data and and show interesting insights

**Comment by Crola1702** [comment]
Buildtimes between Linux noble and jammy show that Jammy generally took more time to build

> **Note:**
> csv data from [`ciros2_noble_vs_jammy_buildtime.csv`](https://github.com/osrf/buildfarm-tools/files/15297785/ciros2_release_buildtime.csv)
> * Contains only builds that are run in linux-2xlarge machines
> * Builds from noble are taken since 2024-04-17
> * Builds from jammy are taken before that date
> * Sample size is the last 100 builds from each job (only the ones that didn't fail)

Here are the results:

| Job Name | Average Buildtime (minutes) | Standard Deviation (minutes) | Sample Size |
|:-------|-----------------------------:|------------------------------:|------------:|
| nightly_linux_repeated (noble) | 123.535 | 18.144 | 17 |
| nightly_linux_repeated (jammy) | 147.016 | 41.882 | 43 |
| nightly_linux_debug (noble) | 77.377 | 19.503 | 24 |
| nightly_linux_debug (jammy) | 88.076 | 29.931 | 71 |
| nightly_linux_release (noble) | 77.841 | 17.089 | 16 |
| nightly_linux_release (jammy) | 83.012 | 27.631 | 51 |

**Comment by Crola1702** [comment]
CC: @clalancette

**Comment by clalancette** [comment]
Huh, very interesting.  Not at all what I expected.

The reason I brought this up to start with is that I was looking at these two jobs:

* [Rolling on Jammy on 2xlarge](https://ci.ros2.org/view/nightly/job/nightly_linux_release/3029/) - 37 minutes
* [Rolling on Noble on 2xlarge](https://ci.ros2.org/view/nightly/job/nightly_linux_release/3070/) - 94 minutes

But given that the overall trend is shorter build times, maybe it isn't worth further investigation.  If you are OK with these numbers, then I'm OK with it too.

**Comment by Crola1702** [comment]
For the example you're showing specifically, the Noble one was the first build of `nightly_linux_release` in that node. When this happens, the node is unable to use cache, so the build takes more time. For Jammy one, this wasn't the case, however, it took a lot less. 

More information about the first build of nodes in Noble vs Jammy Jobs (all times in minutes):

| Job Name | Average Normal Buildtime | Average Node First Buildtime | Difference |
|:-------|-----------------------------:|------------------------------:|------------:|
| nightly_linux_debug (noble) | 55.284 | 88.766 | 33.482 |
| nightly_linux_debug (jammy) | 83.897 | 99.662 | 15.765 |
| nightly_linux_release (noble) | 63.951 | 84.653 | 20.701 |
| nightly_linux_release (jammy) | 76.238 | 94.847 | 18.609 |
| nightly_linux_repeated (noble) | 108.569 | 131.699 | 23.130 |
| nightly_linux_repeated (jammy) | 135.005 | 154.870 | 19.865 |

**Comment by clalancette** [comment]
@Crola1702 Given your findings, what do you think about closing this one out?
